version: '3'

services:
    app:
        build:
            context: .

        env_file:
            - .env

    database:
        image: postgres:16.2
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: test
        volumes:
            - database-volume:/var/lib/postgresql/data


volumes:
    database-volume:
        driver: local