CREATE TABLE TZDB_ERROR_LOG
(
    ERROR_ID      SERIAL PRIMARY KEY,
    ERROR_DATE    DATE NOT NULL DEFAULT now(),
    ERROR_MESSAGE TEXT NOT NULL DEFAULT ''
);

CREATE TABLE TZDB_TIMEZONES
(
    COUNTRY_CODE VARCHAR(2)   NOT NULL,
    COUNTRY_NAME VARCHAR(100) NOT NULL,
    ZONE_NAME    VARCHAR(100) NOT NULL PRIMARY KEY,
    GMT_OFFSET   INT          NOT NULL,
    IMPORT_DATE  DATE         NOT NULL DEFAULT now()
);

CREATE TABLE TZDB_ZONE_DETAILS
(
    COUNTRY_CODE VARCHAR(2)   NOT NULL,
    COUNTRY_NAME VARCHAR(100) NOT NULL,
    ZONE_NAME    VARCHAR(100) NOT NULL,
    GMT_OFFSET   INT          NOT NULL,
    DST          INT          NOT NULL,
    ZONE_START   INT          NOT NULL,
    ZONE_END     INT          NOT NULL,
    IMPORT_DATE  DATE         NOT NULL DEFAULT now(),
    PRIMARY KEY (ZONE_NAME, ZONE_START, ZONE_END)
);